[colors]
background = "#212337"
foreground = "#ebfafa"
primary = "#37f499"
secondary = "#04d1f9"
accent = "#a48cf2"
success = "#a48cf2"
warning = "#86f8c1"
error = "#f16c75"
surface = "#292e42"
border = "#646d8e"
muted_text = "#abb4da"
text = "#ebfafa"
playback_bar_bg = "#292e42"
active_tab = "#ebfafa"
inactive_tab = "#abb4da"
selected_item = "#31374f"
progress_filled = "#37f499"
progress_empty = "#31374f"
lyrics_played = "#abb4da"
lyrics_current = "#37f499"
lyrics_upcoming = "#ebfafa"
